model:
  base_model_type: "realisticVisionV60B1_v51VAE"
  model_path: "resources/models"
  text_to_video_mm_path: "resources/models/fancyvideo_ckpts/vae_3d_61_frames/mp_rank_00_model_states.pt"
  base_model_path: "resources/models/sd_v1-5_base_models/realisticVisionV60B1_v51VAE.safetensors"
  res_adapter_type: "res_adapter_v2"
  trained_keys: ["motion_modules.", "conv_in.weight", "fps_embedding.", "motion_embedding."]
  vae_type: "vae_3d"
  use_fps_embedding: true
  use_motion_embedding: true
  common_positive_prompt: ""
  common_negative_prompt: ""

inference:
  infer_mode: "i2v"
  resolution: [768, 768]
  video_length: 16
  output_fps: 25
  cond_fps: 25
  cond_motion_score: 3.0
  use_noise_scheduler_snr: true
  seed: 22
  prompt_path: "resources/demos/test_prompts/test_i2v_prompt.txt"
  reference_image_folder: "resources/demos/reference_images/768x768"
  output_folder: "resources/demos/samples/i2v/realisticVisionV60B1_v51VAE/768x768"
